### ISSUE TITLE
SSL Path Problems 

### ISSUE THREAD

**Issue by apidev234** [LienJS/Lien#66]
https://stackoverflow.com/questions/69879083/ssl-certificate-in-lien

I Posted My Ques There, I Would Appreciate For Help ;-;

**Comment by IonicaBizau** [comment]
That seems to be a typo -- it should be `cert` instead of `cer`:

    let server = new Lien({
       host: "localhost"
     , port: 5000
     , ssl: {
          // v---- This has to be `cert`
          cert: path.join(__dirname + '/' + 'certificate.cer'),
          key: path.join(__dirname + '/' +'privatekey.txt')
       }
    });
